export const RECEIVE_EVENTS = {
  CONNECTED: 'CONNECTED',
  DISCONNECTED: 'DISCONNECTED',
  YOU_HOST: 'YOU_HOST',
  JOINED: 'JOINED',
  SDP: 'SDP',
  CANDIDATE: 'CANDIDATE',
  COMPLETED: 'COMPLETED'
} as const

export const SEND_EVENTS = {
  ENTER: 'ENTER',
  EXIT: 'EXIT',
  CANDIDATE: 'CANDIDATE',
  SDP: 'SDP',
  COMPLETE: 'COMPLETE'
} as const
