export const CONNECTION_STATE = {
  CLOSED: 'CLOSED',
  CONNECTED: 'CONNECTED'
} as const

export const RECEIVE_EVENTS = {
  CONNECTED: 'CONNECTED',
  DISCONNECTED: 'DISCONNECTED',
  JOINED: 'JOINED',
  SDP: 'SDP',
  CANDIDATE: 'CANDIDATE',
  COMPLETED: 'COMPLETED'
} as const

export const SEND_EVENTS = {
  ENTER: 'ENTER',
  CANDIDATE: 'CANDIDATE',
  SDP: 'SDP',
  COMPLETE: 'COMPLETE'
} as const
